### ISSUE TITLE
Staging from csv

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowballer#2]
Staging from csv is not working but it does not return an error message but instead gives me this. The upload goes through great (here and on the Upload Running List tab as well), but it doesn't actually stage the papers. I get this:

![Screen Shot 2020-08-11 at 4 08 49 PM](https://user-images.githubusercontent.com/30132655/89949254-3cae2800-dbed-11ea-905f-197d2c92fcef.png)

Thoughts?

**Comment by mcweenysean** [comment]
When uploading, I get this warning 8 times: 

Warning: Unknown or uninitialised column: `RId`.

And this message before the one I posted above.

![Screen Shot 2020-08-11 at 4 19 32 PM](https://user-images.githubusercontent.com/30132655/89950131-98c57c00-dbee-11ea-903c-5227e0b5d49b.png)

**Comment by yjunechoe** [comment]
So this seems to be an issue with being unable to find MAG IDs for the papers in the file that was uploaded (so not about the "stage from csv" functionality itself)

I just ran it using the _test_titles.csv_ file you sent me and it works fine, so maybe double check that the file that was uploaded is in the proper format?

And with regards to this error - **Warning: Unknown or uninitialised column: `RId`.** - you can ignore that. That's just a warning saying that the paper found in the database does not have any references stored for it (unfortunate but not fatal).

Here's a gif of how it _should_ go. If you can upload a video of how it fails for you I can probably diagnose it better

![snowballer_issue_2](https://user-images.githubusercontent.com/52832839/89989765-5b2f2480-dcbc-11ea-857c-ca902b406e02.gif)

**Comment by mcweenysean** [comment]
interesting - so the titles paper I was using had 0 incorrect titles (I removed the few that didn't work from the test_titles.csv I sent you). When I use the original test_titles it works great (though it takes 30 seconds to populate the staged papers).

It seems that the function actually doesn't like perfect files. See the gif below

![snowballer_18_matched_title480p](https://user-images.githubusercontent.com/30132655/90049727-d849a200-dc9a-11ea-866a-238c31504588.gif)
