### ISSUE TITLE
search getting stuck on a specific paper

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowballer#3]
When I actually run the search on the test_titles I sent you, it gets stuck on a specific paper with this error and this screenshot. It gets stuck like this and I have to restart the app. Does this happen for you?

`Warning: Error in : no such column: NA`

![Screen Shot 2020-08-12 at 1 48 07 PM](https://user-images.githubusercontent.com/30132655/90055236-a9cfc500-dca2-11ea-9d16-e73b98998427.png)

**Comment by yjunechoe** [comment]
Looks like it was getting stuck on an ID that did not have a paper associated with it (2810006327).

I made an exception for these cases and the search can get past that paper now (I didn't go through with the search on 3200 papers to check for sure if this works)

![image](https://user-images.githubusercontent.com/52832839/90096062-4ced1100-dd6d-11ea-87bc-17e3336e45e2.png)

**Comment by mcweenysean** [comment]
nice - thanks
