### ISSUE TITLE
Check if running list is working as anticipated

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowballer#4]
I haven't really dealt with the running list side of things, so I wanted to ask if you could check that it is working as anticipated. I think we could also update the top-colored boxes to maybe be a hybrid of what the running list tab was and what the prepare search tab is. Let me know your thoughts.

**Comment by yjunechoe** [comment]
I don't see any buttons from the running list tab in the new design, so not sure how to test if its working (unless they've been renamed and moved around or something?). Here's a pic of Prepare Search and Run Search tabs from your recent push for you to check if this new design is as intended:

![image](https://user-images.githubusercontent.com/52832839/90474314-f8c4a100-e15f-11ea-8287-345225326638.png)

![image](https://user-images.githubusercontent.com/52832839/90474342-067a2680-e160-11ea-86a8-85eb7c78f726.png)

And by hybrid of the value boxes do you mean like showing all 7 at the top (4 from running list tab and 3 from prepare search tab)? If not, there's several other ways this could be implemented I guess but I'm not gifted in design so if you could just draw like a sketch of what you're thinking of I could look into what that might look like in code. But the idea itself sounds okay though

**Comment by mcweenysean** [comment]
yeah that looks as anticipated for now, but I think the simplest and most useful boxes would be these 

Previously Searched Titles
Papers Ready to Search
Previously-Found Papers Detected
New Papers Detected

**Comment by mcweenysean** [comment]
papers were not able to be staged if there were found anywhere in the running list due to this line:

`dups <- staged_file_searched()$ID[staged_file_searched()$ID %in% c(data$staged$ID, uploaded_list()$ID)]`

I modified it to the code below and it works now. This was present from our initial split into UI and server, but maybe in my modification of the running list layout, it got messed up.

`dups <- staged_file_searched()$ID[staged_file_searched()$ID %in% c(data$staged$ID]`

**Comment by yjunechoe** [comment]
Hey I didn't look at this change super closely but taking out `uploaded_list()$ID` might have consequences down the line. Basically that line is keeping track of duplicates `dups`, so your change is most likely going to cause previously found papers that you upload to appear in the results if your search found them again.

Can you check if this is the case with this change?

**Comment by mcweenysean** [comment]
no worries! It seems to be working in that papers that were previously searched will not be staged, but papers that are merely in the list work just fine. Thanks so much for getting to this.
