### ISSUE TITLE
Warnings for low density (0 citations) and high density (>1000)

### ISSUE THREAD

**Issue by mcweenysean** [yjunechoe/Snowballer#5]
Here is the warning screen I am working on for the uploaded from file titles. 

![Screen Shot 2020-08-25 at 1 22 27 PM](https://user-images.githubusercontent.com/30132655/91212623-15b82180-e6d6-11ea-9fab-749d30fb10b0.png)

I'm trying to use the model you used for the missing papers, but am struggling. Let me know when you have a minute to help me walk through this. 

![Screen Shot 2020-08-25 at 1 25 16 PM](https://user-images.githubusercontent.com/30132655/91212897-78a9b880-e6d6-11ea-93e1-f791a6f49157.png)

**Comment by yjunechoe** [comment]
This is will probably end up being a sizable module, so can we move any development on this to a new branch?

On the command line from the project director, can you do:

1. `git checkout -b module-upload_from_title`
2. `git add .`
3. `git commit -m <message>`
4. `git push origin module-upload_from_title`

This will push whatever you have now into a new branch for us to work on. That way you don't have to wait till the whole thing is figured out to commit it and I can have a look at the current code.

And while you're working on this new branch, just make sure that `git status` says that you're "On branch module-upload_from_title". If it says it's on the master branch instead, do `git checkout module-upload_from_title` and _then_ push your changes as usual with `git add`, `git commit`, and `git push`.

I'll have a look after it's done and we can schedule a meeting later? I'll be pretty busy for at least the next 2 weeks or so but I'll let you know when I'm available

**Comment by mcweenysean** [comment]
sounds like a plan! I have a meeting now, but I'll push after that.

**Comment by mcweenysean** [comment]
completed with low and high-density warnings
